version: '3.8'

services:
  api-gateway:
    container_name: "api-gateway"
    image: findpetregistry.azurecr.io/apigateway
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - pet-service

  auth-service:
    image: findpetregistry.azurecr.io/authservice
    container_name: "auth-service"
    build:
      context: .
      dockerfile: ./Identity/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
    depends_on:
      - sql-server-container
    restart: on-failure

  pet-service:
    image: findpetregistry.azurecr.io/petservice
    container_name: pet-service
    build:
      context: .
      dockerfile: ./PetService.API/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
    depends_on:
      - sql-server-container
    restart: on-failure

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sql-server-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd2024
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "Passw0rd2024", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
