replicaCount: 2

image:
  repository: draho97/apigateway
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: false  
  name: ""     

ingress:
  enabled: false

autoscaling:
  enabled: false