apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.apigateway.name }}
  labels:
    app: {{ include "findme-chart.name" . }}
spec:
  type: {{ .Values.apigateway.service.type }}
  ports:
    - port: {{ .Values.apigateway.service.port }}
      targetPort: {{ .Values.apigateway.service.targetPort }}
      nodePort: {{ .Values.apigateway.service.nodePort }}

  selector:
    app: {{ include "findme-chart.name" . }}
