apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.postservice.name }}
  labels:
    app: {{ include "findme-chart.name" . }}
spec:
  type: {{ .Values.postservice.service.type }}
  ports:
    - port: {{ .Values.postservice.service.port }}
      targetPort: {{ .Values.postservice.service.targetPort }}
  selector:
    app: {{ include "findme-chart.name" . }}
