apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.postservice.name }}
  labels:
    {{- include "findme-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postservice.service.type }}
  ports:
    - port: {{ .Values.postservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "findme-chart.selectorLabels" . | nindent 4 }}
