apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.sqlserver.name }}
  labels:
    app: {{ include "findme-chart.name" . }}
spec:
  type: {{ .Values.sqlserver.service.type }}
  ports:
    - port: {{ .Values.sqlserver.service.port }}
      targetPort: {{ .Values.sqlserver.service.targetPort }}
      protocol: {{ .Values.sqlserver.service.protocol }}

  selector:
    app: {{ include "findme-chart.name" . }}
