apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Values.sqlserver.name }}
  labels:
    app: {{ include "findme-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "findme-chart.name" . }}  
  template:
    metadata:
      labels:
        app: {{ include "findme-chart.name" . }}  
    spec:
      containers:
        - name: sqlserver
          image: "{{ .Values.sqlserver.image.repository }}:{{ .Values.sqlserver.image.tag }}"
          ports:
            - containerPort: {{ .Values.sqlserver.service.containerPort }}
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sqlserver-secret
                  key: SA_PASSWORD
